version: "3.9"

services:
   db:
      image: mongo:latest
      restart: always
      container_name: "db"
      ports:
         - 27017:27017
      volumes: 
         # Persist data
         - mongodb_data_container:/data/db
   api:
      build: .
      restart: always
      depends_on:
         - db
      ports:
         - 8080:8080

volumes:
   mongodb_data_container:
