version: "3.9"

services:
   frontend:
      container_name: frontend
      build:
         context: ./frontend
         dockerfile: Dockerfile
      volumes:
         - './frontend/:/app'
         - '/app/node_modules'
      ports:
         - 3000:3000
      environment:
         - CHOKIDAR_USEPOLLING=true
      depends_on:
         - api
   db:
      image: mongo:latest
      restart: always
      container_name: "db"
      ports:
         - 27018:27017
      volumes: 
         # Persist data
         - mongodb_data_container:/data/db
   api:
      build: .
      restart: always
      depends_on:
         - db
      ports:
         - 8082:8080

volumes:
   mongodb_data_container:
